# Copyright 2025 Matheus Vilano
# SPDX-License-Identifier: Apache-2.0

from pywwise.descriptors import WwiseProperty
from pywwise.enums import EParametricEqFilterType, EMeterScope
from pywwise.objects.abc import WwiseObject
from pywwise.objects.types.sidechain_mix import SidechainMix


class WwiseParametricEq(WwiseObject):
    """
    https://www.audiokinetic.com/en/library/edge/?source=SDK&id=wwiseobject_effect_wwise_parametric_eq.html \n
    A class serving as an interface for getting/setting properties on Wwise objects. This type specifically targets
    the class represented by `EObjectType.WWISE_PARAMETRIC_EQ`.
    """
    attack_time_band1 = WwiseProperty[float]("AttackTimeBand1", float)
    attack_time_band2 = WwiseProperty[float]("AttackTimeBand2", float)
    attack_time_band3 = WwiseProperty[float]("AttackTimeBand3", float)
    attack_time_band4 = WwiseProperty[float]("AttackTimeBand4", float)
    attack_time_band5 = WwiseProperty[float]("AttackTimeBand5", float)
    attack_time_band6 = WwiseProperty[float]("AttackTimeBand6", float)
    attack_time_band7 = WwiseProperty[float]("AttackTimeBand7", float)
    attack_time_band8 = WwiseProperty[float]("AttackTimeBand8", float)
    band_listen = WwiseProperty[int]("BandListen", int)
    dynamics_enable_band1 = WwiseProperty[bool]("DynamicsEnableBand1", bool)
    dynamics_enable_band2 = WwiseProperty[bool]("DynamicsEnableBand2", bool)
    dynamics_enable_band3 = WwiseProperty[bool]("DynamicsEnableBand3", bool)
    dynamics_enable_band4 = WwiseProperty[bool]("DynamicsEnableBand4", bool)
    dynamics_enable_band5 = WwiseProperty[bool]("DynamicsEnableBand5", bool)
    dynamics_enable_band6 = WwiseProperty[bool]("DynamicsEnableBand6", bool)
    dynamics_enable_band7 = WwiseProperty[bool]("DynamicsEnableBand7", bool)
    dynamics_enable_band8 = WwiseProperty[bool]("DynamicsEnableBand8", bool)
    dynamics_listen = WwiseProperty[int]("DynamicsListen", int)
    dynamics_sidechain_ref = WwiseProperty[SidechainMix]("DynamicsSidechainRef", SidechainMix)
    filter_type_band1 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand1", EParametricEqFilterType)
    filter_type_band2 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand2", EParametricEqFilterType)
    filter_type_band3 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand3", EParametricEqFilterType)
    filter_type_band4 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand4", EParametricEqFilterType)
    filter_type_band5 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand5", EParametricEqFilterType)
    filter_type_band6 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand6", EParametricEqFilterType)
    filter_type_band7 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand7", EParametricEqFilterType)
    filter_type_band8 = WwiseProperty[EParametricEqFilterType]("FilterTypeBand8", EParametricEqFilterType)
    frequency_band1 = WwiseProperty[float]("FrequencyBand1", float)
    frequency_band2 = WwiseProperty[float]("FrequencyBand2", float)
    frequency_band3 = WwiseProperty[float]("FrequencyBand3", float)
    frequency_band4 = WwiseProperty[float]("FrequencyBand4", float)
    frequency_band5 = WwiseProperty[float]("FrequencyBand5", float)
    frequency_band6 = WwiseProperty[float]("FrequencyBand6", float)
    frequency_band7 = WwiseProperty[float]("FrequencyBand7", float)
    frequency_band8 = WwiseProperty[float]("FrequencyBand8", float)
    gain_band1 = WwiseProperty[float]("GainBand1", float)
    gain_band2 = WwiseProperty[float]("GainBand2", float)
    gain_band3 = WwiseProperty[float]("GainBand3", float)
    gain_band4 = WwiseProperty[float]("GainBand4", float)
    gain_band5 = WwiseProperty[float]("GainBand5", float)
    gain_band6 = WwiseProperty[float]("GainBand6", float)
    gain_band7 = WwiseProperty[float]("GainBand7", float)
    gain_band8 = WwiseProperty[float]("GainBand8", float)
    num_bands = WwiseProperty[int]("NumBands", int)
    on_off_band1 = WwiseProperty[bool]("OnOffBand1", bool)
    on_off_band2 = WwiseProperty[bool]("OnOffBand2", bool)
    on_off_band3 = WwiseProperty[bool]("OnOffBand3", bool)
    on_off_band4 = WwiseProperty[bool]("OnOffBand4", bool)
    on_off_band5 = WwiseProperty[bool]("OnOffBand5", bool)
    on_off_band6 = WwiseProperty[bool]("OnOffBand6", bool)
    on_off_band7 = WwiseProperty[bool]("OnOffBand7", bool)
    on_off_band8 = WwiseProperty[bool]("OnOffBand8", bool)
    output_level = WwiseProperty[float]("OutputLevel", float)
    process_lfe = WwiseProperty[bool]("ProcessLFE", bool)
    q_band1 = WwiseProperty[float]("QFactorBand1", float)
    q_band2 = WwiseProperty[float]("QFactorBand2", float)
    q_band3 = WwiseProperty[float]("QFactorBand3", float)
    q_band4 = WwiseProperty[float]("QFactorBand4", float)
    q_band5 = WwiseProperty[float]("QFactorBand5", float)
    q_band6 = WwiseProperty[float]("QFactorBand6", float)
    q_band7 = WwiseProperty[float]("QFactorBand7", float)
    q_band8 = WwiseProperty[float]("QFactorBand8", float)
    range_band1 = WwiseProperty[float]("RangeBand1", float)
    range_band2 = WwiseProperty[float]("RangeBand2", float)
    range_band3 = WwiseProperty[float]("RangeBand3", float)
    range_band4 = WwiseProperty[float]("RangeBand4", float)
    range_band5 = WwiseProperty[float]("RangeBand5", float)
    range_band6 = WwiseProperty[float]("RangeBand6", float)
    range_band7 = WwiseProperty[float]("RangeBand7", float)
    range_band8 = WwiseProperty[float]("RangeBand8", float)
    release_time_band1 = WwiseProperty[float]("ReleaseTimeBand1", float)
    release_time_band2 = WwiseProperty[float]("ReleaseTimeBand2", float)
    release_time_band3 = WwiseProperty[float]("ReleaseTimeBand3", float)
    release_time_band4 = WwiseProperty[float]("ReleaseTimeBand4", float)
    release_time_band5 = WwiseProperty[float]("ReleaseTimeBand5", float)
    release_time_band6 = WwiseProperty[float]("ReleaseTimeBand6", float)
    release_time_band7 = WwiseProperty[float]("ReleaseTimeBand7", float)
    release_time_band8 = WwiseProperty[float]("ReleaseTimeBand8", float)
    rolloff_rate_band1 = WwiseProperty[float]("RolloffRateBand1", float)
    rolloff_rate_band2 = WwiseProperty[float]("RolloffRateBand2", float)
    rolloff_rate_band3 = WwiseProperty[float]("RolloffRateBand3", float)
    rolloff_rate_band4 = WwiseProperty[float]("RolloffRateBand4", float)
    rolloff_rate_band5 = WwiseProperty[float]("RolloffRateBand5", float)
    rolloff_rate_band6 = WwiseProperty[float]("RolloffRateBand6", float)
    rolloff_rate_band7 = WwiseProperty[float]("RolloffRateBand7", float)
    rolloff_rate_band8 = WwiseProperty[float]("RolloffRateBand8", float)
    sidechain_scope = WwiseProperty[EMeterScope]("SidechainScope", EMeterScope)
    threshold_band1 = WwiseProperty[float]("ThresholdBand1", float)
    threshold_band2 = WwiseProperty[float]("ThresholdBand2", float)
    threshold_band3 = WwiseProperty[float]("ThresholdBand3", float)
    threshold_band4 = WwiseProperty[float]("ThresholdBand4", float)
    threshold_band5 = WwiseProperty[float]("ThresholdBand5", float)
    threshold_band6 = WwiseProperty[float]("ThresholdBand6", float)
    threshold_band7 = WwiseProperty[float]("ThresholdBand7", float)
    threshold_band8 = WwiseProperty[float]("ThresholdBand8", float)
